### ISSUE TITLE
Issue with loading chat entry in 1.2.4-beta

### ISSUE THREAD

**Issue by bperian** [bperian/vintel#1]
@Mitelin, 
  I opened a new issue. As the original repo is not active anymore we can work directly here.

**Comment by bperian** [comment]
@Mitelin, 
  I replaced the MSI package . Could you check if it works properly now?

**Comment by Mitelin** [comment]
Ok now sound begun to be wierd and this error apper

04/09 07:08:12| <class 'AttributeError'>: module 'PyQt5.QtGui' has no attribute 'QListWidgetItem'
04/09 07:08:12| -- ------------------- --
04/09 07:08:12| -- Unhandled Exception --
04/09 07:08:12|   File "E:\work\Repositories\vintel\src\vi\ui\viui.py", line 964, in addChatEntry
  File "E:\work\Repositories\vintel\src\vi\ui\viui.py", line 949, in _addMessageToChat

04/09 07:08:12| <class 'AttributeError'>: module 'PyQt5.QtGui' has no attribute 'QListWidgetItem'
04/09 07:08:12| -- ------------------- --

**Comment by bperian** [comment]
thank you for the updates. Will open up new issues for those and fix them

**Comment by Mitelin** [comment]
Thx for your work.

**Comment by bperian** [comment]
closing issue
